name: Bug Report
description: Create a report to help us to fix the issue
labels: ["Type: Bug", "triage"]
body:
 - type: markdown
   attributes:
    value: |
     Thanks for taking the time to fill out this bug report!
 - type: textarea
   id: what-happened
   attributes:
    label: Describe the bug. What happened?
    description: Also tell us, what did you expect to happen?
    placeholder: A clear and concise description of what you observe. If applicable, add the steps to reproduce the behavior and screenshots to illustrate your problem.
   validations:
    required: true
 - type: input
   id: version
   attributes:
    label: What version of Weasis are you running?
    placeholder: ex. 4.1.2, commit 1e3190a...
   validations:
    required: true
 - type: dropdown
   id: system
   attributes:
    label: On which system the problem occurs?
    multiple: true
    options:
     - Windows
     - Linux
     - macOS
   validations:
     required: true
 - type: textarea
   id: logs
   attributes:
    label: Relevant log output
    description: Please copy and paste any relevant [log output from Weasis](https://nroduit.github.io/en/tutorials/logging/) or from the DICOM archive.
    render: shell
 - type: textarea
   id: context
   attributes:
    label: Additional contextual elements
    description: Add more contextual information about the problem (e.g. for network issue, give information about anti-virus or network security software, firewall, proxy...).
    placeholder: Contextual elements
    value: "List of contextual elements (e.g. OS version, type of Weasis installer, Graphic card, OpenGL version...)"

